model = "F5TTS_Base"
ref_audio = "F:\\Izhan Internship\\yqx267n9na-1784562650138\\temp\\trimmed_ref_gen.wav"
ref_text = "Sometimes characters completely lose their mind for no good reason, but what happens when they're 100% justified?"
speed = 1.0
nfe_step = 16
gen_text = "Yes, and the voices stitch together smoothly."
output_dir = "F:\\Izhan Internship\\yqx267n9na-1784562650138"
output_file = "podcast_line_1.wav"

[voices]
